// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: proto/nerdbox/services/traces/v1/traces.proto
package traces

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type TTRPCTracesService interface {
	Stream(context.Context, *emptypb.Empty, TTRPCTraces_StreamServer) error
}

type TTRPCTraces_StreamServer interface {
	Send(*Span) error
	ttrpc.StreamServer
}

type ttrpctracesStreamServer struct {
	ttrpc.StreamServer
}

func (x *ttrpctracesStreamServer) Send(m *Span) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterTTRPCTracesService(srv *ttrpc.Server, svc TTRPCTracesService) {
	srv.RegisterService("nerdbox.services.traces.v1.Traces", &ttrpc.ServiceDesc{
		Streams: map[string]ttrpc.Stream{
			"Stream": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(emptypb.Empty)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.Stream(ctx, m, &ttrpctracesStreamServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCTracesClient interface {
	Stream(context.Context, *emptypb.Empty) (TTRPCTraces_StreamClient, error)
}

type ttrpctracesClient struct {
	client *ttrpc.Client
}

func NewTTRPCTracesClient(client *ttrpc.Client) TTRPCTracesClient {
	return &ttrpctracesClient{
		client: client,
	}
}

func (c *ttrpctracesClient) Stream(ctx context.Context, req *emptypb.Empty) (TTRPCTraces_StreamClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "nerdbox.services.traces.v1.Traces", "Stream", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpctracesStreamClient{stream}
	return x, nil
}

type TTRPCTraces_StreamClient interface {
	Recv() (*Span, error)
	ttrpc.ClientStream
}

type ttrpctracesStreamClient struct {
	ttrpc.ClientStream
}

func (x *ttrpctracesStreamClient) Recv() (*Span, error) {
	m := new(Span)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
